codecov:
  token: 38846251-cc32-44bb-8571-4bfd5218634f
  ci:
    - travis
coverage:
  range: 70..100
  precision: 2
  round: down

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: true
  layout: reach diff flags files
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: yes        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: 2019C jacoco master  # branch names that can post comment
  after_n_builds: 5 #e.g., 5. The number of uploaded reports codecov will receive before posting a comment on a pull request.