codecov:
  token: 38846251-cc32-44bb-8571-4bfd5218634f
  require_ci_to_pass: yes

coverage:
  range: 70..100
  precision: 2
  round: down
  status:
    project:
      default:
        # basic
        target: auto
        threshold: null
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
        status:
          project:
            default: false  # disable the default status that measures entire project
            tests:  # declare a new status context "tests"
              target: 100%  # we always want 100% coverage here
              paths: "tests/"  # only include coverage in "tests/" folder
            app:  # declare a new status context "app"
              paths: "!tests/"  # remove all files in "tests/"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: reach, diff, flags, files
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: yes        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: 20192C          # branch names that can post comment
  after_n_builds: <number> #e.g., 5. The number of uploaded reports codecov will receive before posting a comment on a pull request.


