codecov:
  ci:
    - travis

coverage:
  precision: 2
  round: down
  range: "50...90"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: 2019C master         # branch names that can post comment
  after_n_builds: <number> #e.g., 5. The number of uploaded reports codecov will receive before posting a comment on a pull request.